#!/bin/sh

# Wrapper script for launching fa_zoomer application build by Matlab compiler,
# derived from fa_zoomer_bin script generated by the same tool.

MCRROOT='@MCRROOT@'

# Joins arguments into a : separated path expression
join() { sep=; for x; do echo -n "$sep$x"; sep=:; done; }

MCRJRE="$MCRROOT/sys/java/jre/glnx86/jre/lib/i386"
export LD_LIBRARY_PATH="$(join \
    "$MCRROOT/bin/glnx86" "$MCROOT/sys/os/glnx86" \
    "$MCRJRE/native_threads" "$MCRJRE/server" "$MCRJRE/client" \
    "$MCRJRE")"
export XAPPLRESDIR="$MCRROOT/X11/app-defaults"

exec "$(dirname "$0")"/fa_zoomer_bin "$@"
