#!/bin/sh

# Wrapper script for launching fa_zoomer application build by Matlab compiler,
# derived from fa_zoomer_bin script generated by the same tool.

MCRROOT="@MCRROOT@"

export LD_LIBRARY_PATH=$MCRROOT/bin/glnx86:$MCROOT/sys/os/glnx86
MCRJRE=${MCRROOT}/sys/java/jre/glnx86/jre/lib/i386
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/native_threads
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/server
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/client
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}

export XAPPLRESDIR=${MCRROOT}/X11/app-defaults

exec "$(dirname "$0")"/fa_zoomer_bin "$@"
