#!/bin/sh

# Runs the FA archiver for the booster ring.  This runs on the fa-archiver
# server in parallel with the SR archiver, but servers on port 8889.

ARCHIVE_FILE=/dev/br_archive
ARCHIVE_NAME=BR
SNIFFER_DEV=/dev/fa_sniffer/pci-0000:03:00.0
FA_ID_LIST=/home/ops/diagnostics/config/fa-ids.br
EXTRA_ARGS=(-X -s 8889)

source "$(dirname "$0")"/run_archiver
