#!/bin/sh

# Runs the FA archiver for the lab.  This runs on pc0035, see TS.conf

ARCHIVE_FILE=/scratch/fa-sniffer.bin
ARCHIVE_NAME=TS
SNIFFER_DEV=/dev/fa_sniffer0
FA_ID_LIST=/home/ops/diagnostics/config/fa-ids.ts
EXTRA_ARGS=(-t -X)

source "$(dirname "$0")"/run_archiver
