#!/bin/sh

IOC_NAME='CS-DI-IOC-10'
SAMPLE_SIZE=4096
TARGET_COUNT=$((15 * 5))        # Update every five minutes
FREQUENCIES='arange(1,301)'
LOCATION=SR
ID_LIST="$(seq -s, 172),$(seq -s, 181 186)"

QUALIFIER='-Q1,SR-DI-DCCT-01:SIGNAL'


cd "$(dirname "$0")"/..
exec python/fa-spectrum \
    -I"$IOC_NAME" -s"$SAMPLE_SIZE" -t"$TARGET_COUNT" -F"$FREQUENCIES" \
    $QUALIFIER \
    "$LOCATION" "$ID_LIST"
