#!/bin/sh

# Runs the FA archiver for the booster ring.  This runs on the booster archiver,
# server cs03r-cs-serv-03

ARCHIVE_FILE=/archive/fa-archive
SNIFFER_DEV=/dev/fa_sniffer0
ARCHIVE_PORT=8888

ARCHIVE_ARGS="-X -c filters/decimate.config -s $ARCHIVE_PORT"

cd "$(dirname "$0")"/..
exec build/$(uname -m)/fa-archiver \
    $* $ARCHIVE_ARGS -d "$SNIFFER_DEV" "$ARCHIVE_FILE"
