#!/bin/sh

# These definitions are designed to be overridden by the installer.
PYTHON=dls-python
HERE="$(dirname "$0")"

# Ensure that falib is on the python path
export PYTHONPATH="$HERE${PYTHONPATH:+:}$PYTHONPATH"
exec $PYTHON "$HERE"/audio/audio.py "$@"
